### PR TITLE
Fabo/2030 no validator page

### LINKED ISSUE #2030: Staking page not rendering any content
**Describe the bug**
Staking page for a specific validator is not rendering any content.

**To Reproduce**
1. Go to https://voyager-staging.interblock.io/#/staking/validators/cosmosvaloper1au4wmenqwk2pfa9468tw4ln8mzdswerghen4ca

**Expected behavior**
Something should show up

**Screenshots**
screen shot 2019-02-20 at 12 40 00

**Desktop (please complete the following information):**
Chrome 72 on macOS

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2030

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/vuex/getters.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const pool = state => state.pool
 export const stakingParameters = state => state.stakingParameters
 export const bondDenom = getters =>
   getters.stakingParameters.parameters &&
-  getters.stakingParameters.parameters.bond_denom
+  getters.stakingParameters.parameters.bond_denom || `token`
```
Comment (fedekunze) [inline app/src/renderer/vuex/getters.js]:
```suggestion
  getters.stakingParameters.parameters.bond_denom || `stake`
```

File: app/src/renderer/vuex/getters.js [hunk 2]
```diff
@@ -83,7 +83,7 @@ export const depositDenom = getters =>
   getters.governanceParameters.loaded &&
   getters.governanceParameters.parameters.deposit.min_deposit
     ? getters.governanceParameters.parameters.deposit.min_deposit[0].denom
-    : ``
+    : `token`
```
Comment (jbibla) [inline app/src/renderer/vuex/getters.js]: ...?

Comment (faboweb) [reply app/src/renderer/vuex/getters.js]: only a fallback value as long as the actual denom is not loaded.

Comment (faboweb) [reply app/src/renderer/vuex/getters.js]: so if we use something like: "You can use your `denomDeposit`s to vote". It would read better for the user while loading.

Comment (faboweb) [reply app/src/renderer/vuex/getters.js]: To avoid what happen here:
https://files.slack.com/files-pri/T564PPNET-FGC3GBTB6/image.png
