### PR TITLE
Jordan/1572 scroll bug

### LINKED ISSUE #1572: Scrolling bug on TabMyDelegations
**Description:**

There's a scroll related bug on the `TabMyDelegations` page that displays an empty page (see screenshot).

**Steps to reproduce** (using `yarn start` with old testnet):

1. Go to `Staking` > tab `Validators`
2. Scroll all the way to the bottom of the validators index
3. Click tab `My Delegations`
4. Tab displays empty page

screen shot 2018-11-14 at 12 02 17 pm

### PR DESCRIPTION
**Pull request by jbibla**
Closes #1572 

_Description:_

- added perfect scroll to `PageStaking` and `PageGovernance` so when switching tabs the user is brought to the top of the page.
- vue router's built in scroll behaviour doesn't work for us at the moment because of many previous styling choices

❤️ Thank you!

---

- [x] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [x] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

File: app/src/renderer/components/governance/PageGovernance.vue [hunk 1]
```diff
@@ -66,6 +67,12 @@ export default {
     // TODO: get min deposit denom from gov params
     ...mapGetters([`proposals`, `filters`, `bondingDenom`, `connected`])
   },
+  mounted() {
```
Comment (faboweb) [inline app/src/renderer/components/governance/PageGovernance.vue]: how about putting this logic into TmPage?

Comment (jbibla) [reply app/src/renderer/components/governance/PageGovernance.vue]: i know 😞... but i want to get rid of TmPage and also only should run where tabs are present (not on wallet, transactions, or preferences). also, after we bring tendermint-ui into voyager this kind of thing will be easier / more obvious.

Comment (fedekunze) [reply app/src/renderer/components/governance/PageGovernance.vue]: there's an issue for it on #1391
