### PR TITLE
Fabo/2301 keybase request throttle

### LINKED ISSUE #2301: Keybase requests are inefficient and failing
**Describe the bug**

- [ ] keybase requests are failing sporadically
- [ ] we can request ONLY the avatar - instead of receiving the whole user object and parsing it out locally
    - https://keybase.io/docs/api/1.0/call/user/lookup
    - https://keybase.io/docs/api/1.0/user_objects
- [ ] failed keybase requests don't need a notify

**To Reproduce**
- visit the validators table

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2301 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/vuex/modules/keybase.js [hunk 1]
```diff
@@ -75,3 +69,35 @@ export default () => {
     mutations
   }
 }
+
+async function lookupId(state, keybaseId) {
```
Comment (jbibla) [inline app/src/renderer/vuex/modules/keybase.js]: why do we ever need the ID?

File: app/src/renderer/vuex/modules/keybase.js [hunk 2]
```diff
@@ -75,3 +69,35 @@ export default () => {
...
+        avatarUrl: user.pictures.primary.url,
+        userName: user.basics.username,
+        profileUrl: `https://keybase.io/` + user.basics.username
+      }
+    }
+  }
+}
+
+async function lookupUsername(state, username) {
+  const urlPrefix = `https://keybase.io/_/api/1.0/user/lookup.json?usernames=`
```
Comment (jbibla) [inline app/src/renderer/vuex/modules/keybase.js]: i believe you're still requesting the full user object...

```
User objects are massive

...

To avoid getting more data than you need, you can (should!) specify a comma-separated list of fields you desire. Acceptable values are:

pictures
basics
public_keys
profile
proofs_summary
remote_key_proofs
sigs
cryptocurrency_addresses NEW
```

from https://keybase.io/docs/api/1.0/call/user/lookup

File: app/src/renderer/vuex/modules/keybase.js (hunk 1 above)
Comment (faboweb) [reply app/src/renderer/vuex/modules/keybase.js]: we get the ID from chain, the validators only enter the ID

File: app/src/renderer/vuex/modules/keybase.js (hunk 2 above)
Comment (faboweb) [reply app/src/renderer/vuex/modules/keybase.js]: Nice tip

File: app/src/renderer/vuex/modules/keybase.js [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import axios from "axios"
+import moment from "moment"
```
Comment (sabau) [inline app/src/renderer/vuex/modules/keybase.js]: I think moment is being used through the externals
