### PR TITLE
peng/design checkup windows

### LINKED ISSUE #524: Design checkup on windows
> Thank you for filing an issue!

### Version

0.4.3

### Description

The design on Windows has some flaws like some text looks flaky. Can we do a checkup of the design there?

### LINKED ISSUE #685: light theme broken
> Thank you for filing an issue!

### Version

Commit: d7096b3609e22eeb3db77ada76e92727af942ea1

### Description

The text in the buttons is not readable:

image

### PR DESCRIPTION
**Pull request by nylira**
### Issue
Closes #524 
Closes #685 

### Screenshots

---

- [x] fix light theme primary buttons

**before**
39915276-c874381c-5507-11e8-9d17-3e4924087c88
**after**
screen shot 2018-05-15 at 1 15 34 pm

---

- [x] light theme improvement: darken light backgrounds

**before**
screen shot 2018-05-15 at 1 13 55 pm
**after**
screen shot 2018-05-15 at 1 13 40 pm

---

- [x]  fix ugly background color on onboarding text in light theme 

**before**
screen shot 2018-05-15 at 1 12 22 pm
**after**
screen shot 2018-05-15 at 1 12 27 pm

---

- [x]  fix ugly scrollbars in signin and onboarding

**before**
screen shot 2018-05-15 at 1 20 55 pm
**after** (uses PerfectScrollbar)
screen shot 2018-05-15 at 1 20 02 pm

---

- [x] fix too light of font-weight on Windows
- [x] add separation border between Windows file menu and the Electron viewport

 @faboweb Can you please help me test the last three items on your Windows development environment?

### CODE REVIEW

**Comment by nylira** [comment]
The e2e test was broken for a while for some reason (e2e could not find the right button to press), but I forced a rebuild without cache and now its fixed.

**Comment by faboweb** [comment]
Sign up still looks kind of ugly:
image

Rest looks good 🌷

**Comment by nylira** [comment]
### light theme onboarding
Resolved by using transparent backgrounds for the images.

screen shot 2018-05-16 at 2 58 54 pm

### scrollbar on input field for seed
Resolved by using `autosize` lib to always set textarea height to fit length of seed

screen shot 2018-05-16 at 3 30 26 pm
screen shot 2018-05-16 at 3 30 18 pm

### default scrollbars for NiSession components
Resolved by replacing them with PerfectScrollbar

screen shot 2018-05-16 at 3 32 07 pm
screen shot 2018-05-16 at 3 02 45 pm

**Comment by nylira** [comment]
I believe this is ready to be merged. I have to admit, the look of the light theme is growing on me.

File: app/src/renderer/vuex/modules/themes.js [hunk 1]
```diff
@@ -17,15 +11,22 @@ export default ({ commit }) => {
...
       localStorage.setItem("appTheme", theme)
     },
     updateTheme(state, theme) {
-      setCssVars(state.options[theme])
+      const newTheme = state.options[theme]
+      const isWin = navigator.platform.toUpperCase().indexOf("WIN") >= 0
+      if (isWin) {
+        document.documentElement.style.setProperty(`--font-weight`, 400)
+      }
+      for (let key in newTheme) {
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/themes.js]: why did you remove this refactoring?

File: app/src/renderer/components/common/NiFieldSeed.vue [hunk 2]
```diff
@@ -15,13 +16,18 @@ export default {
       this.$emit("input", value)
     }
   },
-  props: ["value"]
+  mounted() 
+    // adjust the textarea element height to match content
```
Comment (faboweb) [inline app/src/renderer/components/common/NiFieldSeed.vue]: added a small comment about what this plugin does

File: app/src/renderer/vuex/modules/themes.js (hunk 1 above)
Comment (nylira) [reply app/src/renderer/vuex/modules/themes.js]: Coverage reasons, and difficulty of testing that function since (1) I didn’t feel like mocking document was worth it and (2) it’s not being exported. The function was also not being reused anywhere, so putting it inline makes the code easier to follow.

Comment (faboweb) [reply app/src/renderer/vuex/modules/themes.js]: Thank your for clarifying
