### PR TITLE
Fabo/2305 fixed unbonding and redelegation transactions

### LINKED ISSUE #2305: Redelegation amount is broken
**Describe the bug**

The amount on the redelegation tx in the transaction list is showing NaN.

**To Reproduce**

- redelegate
- go to page transactions

**Expected behavior**

it should show the correct redelgation amount

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari
 - Version: 12.0.3

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2305 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/components/transactions/LiStakeTransaction.vue [hunk 1]
```diff
@@ -58,9 +58,7 @@
         Undelegation
         <b>
           {{
-            full(
-              calculatePrettifiedTokens(tx.validator_address, tx.shares_amount)
-            )
+            calculatePrettifiedTokens(tx.validator_address, tx.shares_amount)
```
Comment (fedekunze) [inline app/src/renderer/components/transactions/LiStakeTransaction.vue]: does `calculatePrettifiedTokens` include `full` ?

Comment (faboweb) [reply app/src/renderer/components/transactions/LiStakeTransaction.vue]: Yes, that's why it includes "prettified"
