### PR TITLE
Fabo/2024 fix url params

### LINKED ISSUE #2024: config.js is not using environment variables
**Describe the bug**

`RPC=xxx yarn start` is not using `xxx` as rpc endpoint.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2024 

**Description:**

Thank you! 🚀

---

For contributor:

- [x] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/helpers/url.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ export function getURLParams(window) {
   const queries = window.location.search.slice(1).split(`&`)
   return queries.reduce((config, current) => {
     const [name, value] = current.split(`=`)
-    if ([`stargate`, `rpc`].includes(name)) {
+    if ([`stargate`, `rpc`, `dev`].includes(name)) {
```
Comment (jbibla) [inline app/src/helpers/url.js]: `dev` or `devMode`?

Comment (faboweb) [reply app/src/helpers/url.js]: I could go with either.

Comment (jbibla) [reply app/src/helpers/url.js]: was also thinking lately that perhaps we should change this from `dev` to `insecure` as i don't like conflating "developer mode / feature flags" with the sign in / seed changes. but this can be discussed as a separate issue.

Comment (jbibla) [reply app/src/helpers/url.js]: > I could go with either.

let's use `devMode` then - as this matches the property in the module.

File: app/src/renderer/scripts/boot.js [hunk 2]
```diff
@@ -117,7 +126,5 @@ export const main = async (
   start = startApp
 ) => {
   const params = getURLParams(window)
-  const enrichedConfig = Object.assign({}, _config, params)
-
-  await start(enrichedConfig)
+  await start(params, _config)
```
Comment (jbibla) [inline app/src/renderer/scripts/boot.js]: what is `_config`?

Comment (faboweb) [reply app/src/renderer/scripts/boot.js]: the config file import. the name has the lodash to prevent naming conflicts.
