### PR TITLE
Fix transactions reading and tests

### LINKED ISSUE #1879: missing transaction page no-data-message
UI Version: 0.X.X

Description:

screen shot 2019-01-24 at 12 10 30 am

### LINKED ISSUE #1947: error fetching balances
Description:

This notification appears when the user doesn't have any coins

### LINKED ISSUE #1960: Cannot read property code of undefined
Description:

Sending a transaction passes but renders an error on the modal:

`Sending tokens failed: Cannot read property 'code' of undefined`

screen shot 2019-02-11 at 11 03 12 am

### PR DESCRIPTION
**Pull request by sabau**
screenshot 2019-02-18 at 11 12 53
Closes #1879 

 As side effects:
Closes #1960 
Closes #1947 

_Description:_
- payload changed, so we need to update our prop names / structure to it
- start introducing defensive programming, it happens too often that things changes in an unexpected way, same hash => different payloads/parameters/behaviour. We should then expect this as normal and code properly to handle those situations / errors so users won't be left alone wondering what's happening, then with Sentry we can act on the collected logs
- Reading transaction body aligned
- `hash` replaced with `txhash`
- writing transactions succesfully

❤️ Thank you!

---

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

File: app/src/renderer/components/common/TmPage.vue [hunk 1]
```diff
@@ -80,7 +81,7 @@ export default {
       default: ``
     },
     error: {
-      type: Object,
+      type: Object | Error,
```
Comment (fedekunze) [inline app/src/renderer/components/common/TmPage.vue]: what is this `|` ?

File: app/src/renderer/components/wallet/PageTransactions.vue [hunk 2]
```diff
@@ -56,8 +56,8 @@ export default {
     time
   }),
   computed: {
-    ...mapState([`transactions`]),
     ...mapGetters([
+      `transactions`,
```
Comment (fedekunze) [inline app/src/renderer/components/wallet/PageTransactions.vue]: where are we using this ?

File: test/unit/specs/components/wallet/PageTransactions.spec.js [hunk 3]
```diff
@@ -1,33 +1,63 @@
...
+    wallet: {
+      address: `tb1d4u5zerywfjhxuc9nudvw`
+    },
+    transactions: {
+      loading: false,
+      loaded: true,
+      error: undefined
+    },
+    delegation: {
+      unbondingDelegations: {} // todo add some
```
Comment (fedekunze) [inline test/unit/specs/components/wallet/PageTransactions.spec.js]:
```suggestion
      unbondingDelegations: {} // TODO: add some
```

File: test/unit/specs/store/json/txs.js [hunk 4]
```diff
@@ -10,28 +10,9 @@ export default [
...
-                  coins: [
-                    {
-                      denom: `jbcoins`,
-                      amount: `1234`
-                    }
-                  ],
-                  address: `tb1d4u5zerywfjhxuc9nudvw`
-                }
-              ]
+              from_address: `tb1da6xsetjg9jxgun9wdesexv05j`,
```
Comment (fedekunze) [inline test/unit/specs/store/json/txs.js]: I don't want to be too picky but the prefix should be `cosmos` instead of `tb` in all mocked addresses

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (sabau) [reply app/src/renderer/components/common/TmPage.vue]: Object or Error, I received sometimes this warning by Vue

File: app/src/renderer/components/wallet/PageTransactions.vue (hunk 2 above)
Comment (sabau) [reply app/src/renderer/components/wallet/PageTransactions.vue]: at the header we are forwarding `loading`, `loaded` and `error` to the Page component, I found a getter less invasive than the mapState, and this was the only place in the whole codebase where mapState was used so, I proposed to drop it :)

File: test/unit/specs/store/json/txs.js (hunk 4 above)
Comment (sabau) [reply test/unit/specs/store/json/txs.js]: Here I tried to keep the snapshot identical by changing only the way the message was built, but we can adhere to the `cosmos` prefix, or have just X, Y, Z as addresses so it's easier to follow the tests

Comment (sabau) [reply test/unit/specs/store/json/txs.js]: I try to propose the A, B addresses, let me know what do you think

**Comment by sabau** [comment]
Just tested:
- transactions displayed
- I can send momey to others and myself
- sent transactions are visible (hash VS txhash fixed)
- test upgraded for trasnactions.js, dropping the old world took me some time

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (faboweb) [reply app/src/renderer/components/common/TmPage.vue]: Didn't we decide to not allow different prop types?

File: app/src/renderer/components/transactions/TmLiBankTransaction.vue [hunk 5]
```diff
@@ -48,22 +48,19 @@ export default {
...
-      return this.tx.inputs[0].address === this.address
+      return this.tx.from_address === this.address
     },
     sender() {
-      return this.tx.inputs[0].address
+      return this.tx.from_address
     },
-    coinsSent() {
-      return this.tx.inputs[0].coins[0]
+    coins() {
```
Comment (faboweb) [inline app/src/renderer/components/transactions/TmLiBankTransaction.vue]: Nice

File: app/src/renderer/vuex/modules/send.js [hunk 6]
```diff
@@ -153,8 +153,8 @@ function assertOk(res) {
     return res.forEach(assertOk)
   }
 
-  if (res.check_tx.code || res.deliver_tx.code) {
-    const message = res.check_tx.log || res.deliver_tx.log
+  if (!(res.height && res.txhash)) {
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/send.js]: Why both?

File: app/src/renderer/vuex/modules/wallet.js [hunk 7]
```diff
@@ -66,10 +66,10 @@ export default ({ node }) => {
       try {
         const res = await node.queryAccount(state.address)
         state.error = null
-        const coins = res.coins || []
-        commit(`setNonce`, res.sequence)
-        commit(`setAccountNumber`, res.account_number)
-        commit(`setWalletBalances`, coins)
+        const { coins, sequence, account_number } = res || {}
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/wallet.js]: Nice

File: test/unit/specs/connectors/lcdClientMock.spec.js [hunk 8]
```diff
@@ -102,6 +102,23 @@ describe(`LCD Client Mock`, () => {
     expect(res.length).toBe(3)
   })
 
+  it(`persists a sent tx to myself`, async () => {
```
Comment (faboweb) [inline test/unit/specs/connectors/lcdClientMock.spec.js]: We don't extend the lcdclientmock anymore

File: app/src/renderer/vuex/modules/send.js (hunk 6 above)
Comment (sabau) [reply app/src/renderer/vuex/modules/send.js]: safety, in theory txhash should be enough

**Comment by sabau** [comment]
Yeah I added a little coverage on lcdmock to pass the circleci test, it's still mandatory to have the coverage there

File: test/unit/specs/connectors/lcdClientMock.spec.js (hunk 8 above)
Comment (sabau) [reply test/unit/specs/connectors/lcdClientMock.spec.js]: the coverage of lcdClientMock decreased once I've changed some test to avoid running send from here, once Ive done that I had to cover that dead piece of code to have the green ✅ from CCI

Comment (faboweb) [reply test/unit/specs/connectors/lcdClientMock.spec.js]: how about instead ignoring coverage on lcdClientMock?

Comment (sabau) [reply test/unit/specs/connectors/lcdClientMock.spec.js]: I think we should keep it working and tested until we don't drop it

File: app/src/config.js [hunk 9]
```diff
@@ -1,8 +1,8 @@
-const dev = process.env.NODE_ENV === `develop`
+const dev = process.env.NODE_ENV === `development`
 const stargate =
   process.env.STARGATE ||
   (dev
-    ? `localhost:8080`
+    ? `http://localhost:8080`
```
Comment (fedekunze) [inline app/src/config.js]: `http` ??

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (fedekunze) [reply app/src/renderer/components/common/TmPage.vue]: I also vote for not having `Error` here

File: test/unit/specs/connectors/lcdClientMock.spec.js (hunk 8 above)
Comment (sabau) [reply test/unit/specs/connectors/lcdClientMock.spec.js]: But one good thing would be stopping importing it from the spec files touched, so that PR will be easier, I'll drop that import from transactions.spec.js

File: app/src/renderer/vuex/modules/send.js [hunk 10]
```diff
@@ -153,8 +153,8 @@ function assertOk(res) {
     return res.forEach(assertOk)
   }
 
-  if (res.check_tx.code || res.deliver_tx.code) {
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/send.js]: does this fixes #1960 ?

File: test/unit/specs/components/transactions/TmLiAnyTransaction.spec.js [hunk 11]
```diff
@@ -8,7 +8,7 @@ describe(`TmLiAnyTransaction`, () => {
   const propsData = {
     transaction: transactions[0],
     validators: state.candidates,
-    address: `tb1da6xsetjg9jxgun9wdesexv05j`,
+    address: `A`,
```
Comment (fedekunze) [inline test/unit/specs/components/transactions/TmLiAnyTransaction.spec.js]: lol I just meant switching the prefix (eg: `cosmos1da6xsetjg9jxgun9wdesexv05j` instead of `tb1da6xsetjg9jxgun9wdesexv05j`)

Comment (fedekunze) [reply test/unit/specs/components/transactions/TmLiAnyTransaction.spec.js]: but nbd

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (sabau) [reply app/src/renderer/components/common/TmPage.vue]: Ok, I'll drop this and when the warnings appear I'll open an issue so we can handle the errors properly

**Comment by fedekunze** [comment]
mind uploading some screenshots, bitte ?

File: app/src/renderer/vuex/modules/send.js (hunk 10 above)
Comment (sabau) [reply app/src/renderer/vuex/modules/send.js]: yep

**Comment by sabau** [comment]
Ok, in theory nothing should change, just updating the payload to SDK changes

File: app/src/config.js (hunk 9 above)
Comment (sabau) [reply app/src/config.js]: Basically by omitting it chrome tries to keep the same level of security as your page, so `https`

But our caddy file comes with no certificates, so if you have a running client and click on those links you should receive:
http://localhost:8080/node_version -> 0.31.2-20-g1aa6c197
https://localhost:8080/node_version -> ERR_SSL_PROTOCOL_ERROR
