### PR TITLE
Fabo/1045 slider bug

### LINKED ISSUE #1045: Wallet Staking - Slider UI Bug
UI Version: 0.9.1

Description: Slider interface bug

- In wallet, under Staking tab
- Select more than 1 validator 
- When trying to Bond 'Steak' after hitting next, there's a graphic slider bug when you slide any slider besides the first selected. 
- Not only Grayed out, but no change to input field

screen shot 2018-07-30 at 4 06 06 am

I believe the problem is only the slider UI because making 'Steak' bond allocation through mouse clicks on the arrows to increase or decrease count OR simply input field seems to be perfectly fine. Problems start when trying to use the slider. 

screen shot 2018-07-30 at 4 18 39 am

### PR DESCRIPTION
**Pull request by faboweb**
Closes #1045 

Description:

Also moved out of bounds message up:
image

Also disabling buttons when sending:
image

❤️ Thank you!

### CODE REVIEW

File: app/src/renderer/components/staking/PageBond.vue [hunk 1]
```diff
@@ -113,8 +115,10 @@ tm-page.page-bond(:title="`Bond ${denom}`")
         v-if='!$v.fields.bondConfirm.required')
 
     div(slot='footer')
-      tm-btn#btn-reset(type="button" @click.native="resetFields" value="Reset" color="danger")
-      tm-btn#btn-bond(value="Submit" color="primary")
+      tm-btn(v-if="delegating" type="button" value="Reset" disabled="true")
+      tm-btn#btn-reset(v-else type="button" @click.native="resetFields" value="Reset" color="danger")
+      tm-btn(v-if="delegating" value="Sending..." disabled="true")
```
Comment (jbibla) [inline app/src/renderer/components/staking/PageBond.vue]: 👏
