### PR TITLE
Send fix

### LINKED ISSUE #694: Voyager doesn't recover from an error while sending coins
> Thank you for filing an issue!

### Version

Commit 220397c93f1555e89971181e4c1a2cc929954de3

### Description

When a sending transaction fails, all following transactions do not produce REST requests.

@mappum maybe?

### PR DESCRIPTION
**Pull request by mappum**
> Thank you a lot for contributing to Cosmos Voyager!

Fixed the issue where the send lock wouldn't get unset when an error occurred, causing future sends to fail. Also added a test case for this to prevent regressions.

### Issue

closes #694 

### Screenshots

❤️ Thank you!

### CODE REVIEW

File: app/src/renderer/vuex/modules/send.js [hunk 1]
```diff
@@ -45,21 +45,27 @@ export default ({ commit, node }) => {
...
-      let res = await lock
-      lock = null
-
-      return res
+      try {
+        // send and unlock when done
+        lock = doSend(...args)
+        // wait for doSend to finish
+        let res = await lock
+        return res
```
Comment (NodeGuy) [inline app/src/renderer/vuex/modules/send.js]: This can be `return await lock`.

File: test/unit/specs/store/send.spec.js [hunk 2]
```diff
@@ -58,5 +58,28 @@ describe("Module: Send", () => {
       await store.dispatch("sendTx", args)
       expect(node.ibcSend.mock.calls).toMatchSnapshot()
     })
+
+    it("should send a transaction after failing", async () => {
```
Comment (faboweb) [inline test/unit/specs/store/send.spec.js]: Good job adding the test for this problem. :) 👍

File: app/src/renderer/vuex/modules/send.js (hunk 1 above)
Comment (faboweb) [reply app/src/renderer/vuex/modules/send.js]: I think the solution is readable enough. I will approve. If @NodeGuy still insists we should improve the code here, I am happy to create another PR.

Comment (NodeGuy) [reply app/src/renderer/vuex/modules/send.js]: OK but in the future if the intention is to clarify then `res` is insufficient.  An English word is always preferable.
