### PR TITLE
David/1446 delegations filters

### LINKED ISSUE #1445: PageStaking and TabValidators have a lot of duplicate code
some examples:

```
somethingToSearch()
vpTotal()
enrichedDelegates()
sortedFilteredEnrichedDelegates()
```

### LINKED ISSUE #1446: filters on my delegations tab do not work
UI Version: 0.10.6

Description:

1. visit my delegation tab
2. click any of the filters from panel sort
3. see nothing happen

### PR DESCRIPTION
**Pull request by NodeGuy**
Closes #1446 and closes #1445 

_Description:_

Refactors validator tables by creating new component `TableValidators`.  Has the effect of fixing column sorting in TabMyDelegations.  Also removes redundant code from PageStaking.

❤️ Thank you!

---

* [x] Added entries in `CHANGELOG.md` with issue # and GitHub username
* [x] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/voyager/issues/1480.

File: app/src/renderer/components/staking/TableValidators.vue [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+    properties() {
+      return [
+        {
+          title: `Moniker`,
+          value: `small_moniker`,
+          tooltip: `The validator's moniker`,
+          class: `name`
+        },
+        {
+          title: `Bonded ${this.bondingDenom}`,
```
Comment (jbibla) [inline app/src/renderer/components/staking/TableValidators.vue]:
```suggestion
          title: `Delegated ${this.bondingDenom}`,
```
