### PR TITLE
Fix Proposal page

### LINKED ISSUE #1908: Refresh proposal status after deposit
It currently doesn't update itself
Same for voting

### PR DESCRIPTION
**Pull request by sabau**
Closes #1908 

**Description:**
- fix accessing the page directly
- number of votes temporary fixed, when we will receive atoms instead of micro atoms this multiplier should be removed

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/components/governance/PageProposal.vue [hunk 1]
```diff
@@ -183,64 +180,55 @@ export default {
...
     },
-    totalVotes() {
-      return (
-        this.tally.yes +
-        this.tally.no +
-        this.tally.no_with_veto +
-        this.tally.abstain
-      )
+    totalVotes({tally: {yes, no, no_with_veto, abstain}} = this) {
+      return (yes + no + no_with_veto + abstain)
```
Comment (faboweb) [inline app/src/renderer/components/governance/PageProposal.vue]: Are these guaranteed to be defined? I.e.: `undefined + 1 + undefined = NaN`

File: app/src/renderer/vuex/modules/governance/proposals.js [hunk 2]
```diff
@@ -25,34 +37,18 @@ export default ({ node }) => {
...
-                final_tally_result = JSON.parse(
-                  JSON.stringify(proposal.value.final_tally_result)
-                )
-              }
-              commit(`setProposalTally`, {
-                proposal_id: proposal.value.proposal_id,
-                final_tally_result
-              })
-            })
+            proposals.map(setProposalTally(commit, node))
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/governance/proposals.js]: nice refactor

File: app/src/renderer/vuex/modules/governance/proposals.js [hunk 3]
```diff
@@ -9,7 +21,7 @@ export default ({ node }) => {
     proposals: {},
     tallies: {}
   }
-  const state = JSON.parse(JSON.stringify(emptyState))
+  const state = {...emptyState}
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/governance/proposals.js]: 👍

**Comment by faboweb** [comment]
unit tests fail

File: app/src/renderer/components/governance/PageProposal.vue (hunk 1 above)
Comment (sabau) [reply app/src/renderer/components/governance/PageProposal.vue]: In theory yes, I tried the counter check and I can't find a way to have this object only partially defined

File: app/src/renderer/vuex/modules/governance/proposals.js (hunk 3 above)
Comment (faboweb) [reply app/src/renderer/vuex/modules/governance/proposals.js]: Note: I think if I edit `state.proposals` I also edit `emptyState.proposals`

**Comment by faboweb** [comment]
conflicts

File: app/src/renderer/vuex/modules/governance/proposals.js [hunk 4]
```diff
@@ -94,6 +80,7 @@ export default ({ node }) => {
         Sentry.captureException(error)
         state.error = error
       }
+      return undefined
```
Comment (jbibla) [inline app/src/renderer/vuex/modules/governance/proposals.js]: why do we want to return `undefined`?

Comment (faboweb) [reply app/src/renderer/vuex/modules/governance/proposals.js]: we did as well before, it is just more explicit this way

Comment (jbibla) [reply app/src/renderer/vuex/modules/governance/proposals.js]: i think a number of our modules do not have any return statements ... ?

File: app/src/renderer/vuex/modules/governance/proposals.js [hunk 5]
```diff
@@ -70,22 +66,12 @@ export default ({ node }) => {
...
-        } else {
-          final_tally_result = JSON.parse(
-            JSON.stringify(proposal.value.final_tally_result)
-          )
-        }
-        commit(`setProposalTally`, { proposal_id, final_tally_result })
+        setProposalTally(commit, node)(proposal)
+        return proposal
       } catch (error) {
         commit(`notifyError`, {
```
Comment (jbibla) [inline app/src/renderer/vuex/modules/governance/proposals.js]: please remove the notify and add loading and loaded properties in the catch block

File: app/src/renderer/vuex/modules/governance/proposals.js (hunk 4 above)
Comment (sabau) [reply app/src/renderer/vuex/modules/governance/proposals.js]: yeah it's what was already happening under the hood, I was thinking is more direct for readers in this way

File: app/src/renderer/vuex/modules/governance/proposals.js (hunk 5 above)
Comment (sabau) [reply app/src/renderer/vuex/modules/governance/proposals.js]: Are you sure? I can't find any other place where we do that

Comment (sabau) [reply app/src/renderer/vuex/modules/governance/proposals.js]: I will move the flag switch after the real action, as it is now it doesn't make sense, I haven't seen this earlier

Comment (sabau) [reply app/src/renderer/vuex/modules/governance/proposals.js]: I think I will never see the error, we had a little discussion with @faboweb about this, I'll open an issue where we can develop

Here the loaded status is shared across `getProposals` and `getProposal`, when you access a proposal that `proposalId` is going to the `proposals` dictionary, but loading, loaded and error are promiscuous, same happen for transactions etc.. 

We were thinking of changing the priority in TmPage so error rule, and error in this case should not come from `proposals.error` but from either:
- `proposals.statuses[proposalId]` if we want a structure with `{loading, loaded, error}`
- `proposals.errors[proposalId]` if we want to store just errors

All this apply only to proposals that got accessed directly from URL, the others won't mind, they are already in the store thanks to `getProposals` and adding a bunch of `true false null` for every proposal scanned is not really useful I think, so we should expect those flags to be also undefined in case of succesfully fetched proposals

This shuold be generic so we can replace the word `proposal` with transaction etc..
