### PR TITLE
fixed some css variables

### LINKED ISSUE #1696: a bunch of broken css variables
UI Version: 0.X.X

Description:

### PR DESCRIPTION
**Pull request by jbibla**
Closes #1696 

_Description:_

- fixed some borked css variables 

❤️ Thank you!

---

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer

### CODE REVIEW

File: app/src/renderer/components/common/TmModal.vue [hunk 1]
```diff
@@ -94,7 +94,7 @@ export default {
 }
 
 .tm-modal-icon i {
-  font-size: lg;
+  font-size: var(--sm);
```
Comment (faboweb) [inline app/src/renderer/components/common/TmModal.vue]: switched from lg to sm on purpose?

Comment (jbibla) [reply app/src/renderer/components/common/TmModal.vue]: nope. thank you for catching.
