### PR TITLE
Fabo/2272 denom convert

### LINKED ISSUE #2272: Show atom instead uatom on mainnet
**Describe the bug**

We show `utam` but show atoms.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2272 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/components/governance/PageProposal.vue [hunk 1]
```diff
@@ -72,9 +72,9 @@
             <dt>Deposit Count</dt>
             <dd>
               {{
-                num.atoms(proposal.total_deposit[0].amount) +
+                totalDeposit.amount +
```
Comment (sabau) [inline app/src/renderer/components/governance/PageProposal.vue]: probably now fit in one line :)

File: app/src/renderer/components/governance/PageProposal.vue [hunk 2]
```diff
@@ -250,6 +250,9 @@ export default {
           message: `There was an error determining the status of this proposal.`,
           color: `grey`
         }
+    },
+    totalDeposit() {
```
Comment (sabau) [inline app/src/renderer/components/governance/PageProposal.vue]: nice moving out of logic from template

File: app/src/config.js [hunk 3]
```diff
@@ -15,7 +15,6 @@ export default {
   name: `Cosmos Voyager`,
   development: dev,
   default_network: `${dev ? `local-` : ``}testnet`,
-  denoms: [`stake`, `photino`],
```
Comment (sabau) [inline app/src/config.js]: bye bye 👍

File: app/src/renderer/scripts/num.js [hunk 4]
```diff
@@ -59,10 +59,27 @@ function uatoms(number = 0) {
...
 
+// convert micro denoms like uatom to display denoms like atom
+function denom(denom) {
+  if (denom.charAt(0) === `u`) {
+    return denom.substr(1)
+  }
+  return denom
+}
+
+function viewCoin({ amount, denom: _denom }) {
```
Comment (sabau) [inline app/src/renderer/scripts/num.js]: denom has been renamed _denom for the upper function name clashing?

File: app/src/renderer/scripts/num.js [hunk 5]
```diff
@@ -59,10 +59,27 @@ function uatoms(number = 0) {
   return BigNumber(number).times(1e6).toString()
 }
 
+// convert micro denoms like uatom to display denoms like atom
+function denom(denom) {
```
Comment (sabau) [inline app/src/renderer/scripts/num.js]: I would change the name here mostly because it's a name used across the codebase, and the function is doing something with the denom, like normalize or demicrodenominatorizer XD

Comment (jbibla) [reply app/src/renderer/scripts/num.js]: i agree with karoly. would be better to have a more explicit name. 

not `demicrodenominatorizer` tho LOL

File: app/src/renderer/scripts/num.js (hunk 4 above)
Comment (faboweb) [reply app/src/renderer/scripts/num.js]: yes, should be named differently?

File: app/src/renderer/scripts/num.js (hunk 5 above)
Comment (faboweb) [reply app/src/renderer/scripts/num.js]: done

File: app/src/renderer/components/governance/ModalDeposit.vue [hunk 6]
```diff
@@ -50,7 +50,7 @@
 
 <script>
 import { mapGetters } from "vuex"
-import { uatoms, atoms, SMALLEST } from "../../scripts/num.js"
+import num, { uatoms, atoms, SMALLEST } from "../../scripts/num.js"
```
Comment (jbibla) [inline app/src/renderer/components/governance/ModalDeposit.vue]: do we need to import `num` and the destructured version?

Comment (faboweb) [reply app/src/renderer/components/governance/ModalDeposit.vue]: we don't I didn't want to do all the refactors here. I volunteer to do the follow up. I think `num.x` is better for search and replace.

File: app/src/renderer/vuex/getters.js [hunk 7]
```diff
@@ -78,7 +80,7 @@ export const pool = state => state.pool
 export const stakingParameters = state => state.stakingParameters
 export const bondDenom = getters =>
   getters.stakingParameters.parameters &&
-  getters.stakingParameters.parameters.bond_denom || `uatom`
+  num.viewDenom(getters.stakingParameters.parameters.bond_denom || `uatom`)
```
Comment (jbibla) [inline app/src/renderer/vuex/getters.js]:
```suggestion
  num.viewDenom(getters.stakingParameters.parameters.bond_denom || `ATOMs`)
```

Comment (faboweb) [reply app/src/renderer/vuex/getters.js]: I think this is wrong here. `bond_denom` in the happy case is `uatom`. No plural, no upper case. If we want to change this, the processing should happen inside `viewDenom`.
