### PR TITLE
Be sure to build when publishing a release.

### LINKED ISSUE #1003: Publish process on CI is missing Voyager build step
UI Version: 0.8.2

Description:

When the publish script is executed, Voyager is not build yet causing the script to fail.

### PR DESCRIPTION
**Pull request by NodeGuy**
Closes #1003 

Description:

❤️ Thank you!

### CODE REVIEW

**Comment by faboweb** [comment]
Please do not skip the git hooks. This bug would have been caught locally.

File: tasks/publish.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 "use strict"
 
+const build = require(`./build/build`)
```
Comment (NodeGuy) [inline tasks/publish.js]: Oops, I had already fixed that myself but it looks like my push failed.  Thanks for catching it.
