### PR TITLE
Fabo/2330 poquito requests 2

### LINKED ISSUE #2330: Rewards not updated
**Describe the bug**

The request to get total rewards is successful, but the components (balance header, withdraw modal, livalidator and pagevalidator) are not being updated to reflect this.

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2330 

Moved throttling of requests into modules.
Properly query once initially and then every 10 blocks.
Also throttling validator (list and signing info updates).

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/vuex/modules/delegates.js [hunk 1]
```diff
@@ -11,7 +11,8 @@ export default ({ node }) => {
     globalPower: null,
     loading: false,
     loaded: false,
-    error: null
+    error: null,
+    lastDelegatesUpdate: 0
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/delegates.js]:
```suggestion
    lastValidatorsUpdate: 0
```

File: app/src/renderer/vuex/modules/delegates.js [hunk 2]
```diff
@@ -58,16 +59,28 @@ export default ({ node }) => {
...
+      {
+        commit,
+        getters: { lastHeader }
+      },
+      validators
+    ) {
+      // throttle the update for validators for every 10 blocks
+      const waited10Blocks =
+        Number(lastHeader.height) - state.lastDelegatesUpdate > 10
+      if (state.lastDelegatesUpdate === 0 || waited10Blocks) {
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/delegates.js]:
```suggestion
      if (state.lastValidatorsUpdate === 0 || waited10Blocks) {
```

File: app/src/renderer/vuex/modules/delegates.js [hunk 3]
```diff
@@ -58,16 +59,28 @@ export default ({ node }) => {
...
+        state.lastDelegatesUpdate = Number(lastHeader.height)
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/delegates.js]:
```suggestion
        state.lastValidatorsUpdate = Number(lastHeader.height)
```

File: app/src/renderer/vuex/modules/delegates.js [hunk 4]
```diff
@@ -58,16 +59,28 @@ export default ({ node }) => {
...
+    async updateSigningInfo(
+      {
+        commit,
+        getters: { lastHeader }
+      },
+      validators
+    ) {
+      // throttle the update for validators for every 10 blocks
+      const waited10Blocks =
+        Number(lastHeader.height) - state.lastDelegatesUpdate > 10
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/delegates.js]:
```suggestion
        Number(lastHeader.height) - state.lastDelegatesUpdate >= 10
```

File: app/src/renderer/components/common/TmBalance.vue [hunk 5]
```diff
@@ -85,8 +86,14 @@ export default {
     lastHeader: {
       immediate: true,
       handler(newHeader) {
-        const waitTenBlocks = Number(newHeader.height) % 10 === 0
-        if (this.session.signedIn && waitTenBlocks) {
+        const height = Number(newHeader.height)
+        // run the update queries the first time and after every 10 blocks
+        const waitedTenBlocks = height - this.lastUpdate > 10
```
Comment (fedekunze) [inline app/src/renderer/components/common/TmBalance.vue]:
```suggestion
        const waitedTenBlocks = height - this.lastUpdate >= 10
```

File: app/src/renderer/vuex/modules/distribution.js [hunk 6]
```diff
@@ -99,16 +101,38 @@ export default ({ node }) => {
...
+    async getRewardsFromMyValidators(
+      {
+        state,
+        dispatch,
+        getters: { lastHeader, yourValidators }
+      }
+    ) {
+      // throttle the update of validator rewards to every 20 blocks
+      const waitedTwentyBlocks =
+        Number(lastHeader.height) - state.lastValidatorRewardsUpdate > 20
```
Comment (fedekunze) [inline app/src/renderer/vuex/modules/distribution.js]:
```suggestion
        Number(lastHeader.height) - state.lastValidatorRewardsUpdate >= 20
```
