### PR TITLE
fedekunze/1917 handle ledger disconnection & rejection

### LINKED ISSUE #1917: Handle ledger disconnection before signing
What happens if the user signs in with ledger and then disconnects before he clicks to sign with ledger?
Should we show an additional note for this?
Is there a bug if this happens?

Scope:
- Check if Ledger is connected when opening ActionModal
- Reconnect if Ledger is not connected

### LINKED ISSUE #1978: connect/disconnect still renders error notifications after timeout
Description:

Expected:

1. try to connect
2. stop connection (click on icon)
4. No errors as not trying to connect

Reality:

1. try to connect
2. stop connection (click on icon)
3. Wait for timeout Ledger app
4. Still renders errors from the previous connection attempt

screen shot 2019-02-13 at 10 23 40 am

### LINKED ISSUE #2016: Signature rejection with Ledger
UI Version: 0.X.X

Description:

We're not handling the case when the user rejects the transaction on the ledger, which results in an error: `signature is not a Buffer`

### PR DESCRIPTION
**Pull request by fedekunze**
Closes #1917 
Closes #1978
Closes #2016 

**Description:**

LedgerSession

screen shot 2019-02-19 at 12 09 15 pm

ActionModal

screen shot 2019-02-18 at 5 50 29 pm

screen shot 2019-02-18 at 5 50 50 pm

Signature rejection

screen shot 2019-02-19 at 4 50 45 pm

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `CHANGELOG.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Nice. I think this needs a design revamp @jbibla

File: app/src/renderer/components/common/TmSessionHardware.vue [hunk 1]
```diff
@@ -44,16 +51,21 @@ export default {
...
     },
+    setConnectionError(error) {
+      this.connectionError = error
+    },
     async connectLedger() {
+      this.setConnectionError(null)
       this.setStatus(`detect`)
-      const connected = await this.$store.dispatch(`connectLedgerApp`)
-      if (connected) {
+      const error = await this.$store.dispatch(`connectLedgerApp`)
```
Comment (faboweb) [inline app/src/renderer/components/common/TmSessionHardware.vue]: this should throw instead of returning an error imo

File: app/src/renderer/vuex/modules/ledger.js [hunk 2]
```diff
@@ -48,24 +48,46 @@ export default () => {
         externals: state.externals
       }
     },
-    /* TODO: Create a function to detect ledger is connected (i.e unlocked with
-      password and on Home app) */
+    async pollLedgerDevice({ state }) {
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/ledger.js]: this should throw instead of returning an error

Comment (sabau) [reply app/src/renderer/vuex/modules/ledger.js]: Fast Failing 🎉

Comment (fedekunze) [reply app/src/renderer/vuex/modules/ledger.js]: updated

File: app/src/renderer/components/common/TmSessionHardware.vue (hunk 1 above)
Comment (fedekunze) [reply app/src/renderer/components/common/TmSessionHardware.vue]: updated

File: app/src/renderer/components/common/ActionModal.vue [hunk 3]
```diff
@@ -57,7 +48,9 @@
         </tm-form-group>
       </div>
       <div v-else-if="step === `sign`" class="action-modal-form">
+        <hardware-state v-if="sending" :loading="true" value="Waiting for signature on app" />
         <hardware-state
+          v-else
           icon="usb"
           value="Please unlock the Cosmos app on your Ledger Nano S"
```
Comment (jbibla) [inline app/src/renderer/components/common/ActionModal.vue]:
```suggestion
          value="Please unlock the Cosmos app on your Ledger Nano&nbsp;S"
```

File: app/src/renderer/components/common/TmSessionLoading.vue [hunk 4]
```diff
@@ -10,7 +10,7 @@
         <img src="~assets/images/loader.svg"><br>{{ message }} &nbsp;
       </div>
       <div class="tm-session-footer">
-&nbsp;
+        &nbsp;
```
Comment (jbibla) [inline app/src/renderer/components/common/TmSessionLoading.vue]: is this necessary? what's going on here?
