### PR TITLE
Jordan/2267+2278 validator table bugs

### LINKED ISSUE #2237: TmPage "managed-body" refactor
The usage of a check on the slot property `this.$slots['managed-body']` smells dirty. Is this really needed?

No proposal yet. Need to discuss. @sabau

### LINKED ISSUE #2267: Sorting on validators do not work
**Describe the bug**

When I click on the sorting on the validators list, none but "My Delegations" works.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### LINKED ISSUE #2278: Commission Percentage is incorrect
Screen Shot 2019-03-14 at 11 39 19 PM

### PR DESCRIPTION
**Pull request by jbibla**
Closes #2267 
Closes #2278 
Closes #2237

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/components/staking/TableValidators.vue [hunk 1]
```diff
@@ -102,36 +107,24 @@ export default {
           } you have delegated to this validator`,
           class: `your-votes`
         },
-        {
-          title: `Rewards`,
```
Comment (fedekunze) [inline app/src/renderer/components/staking/TableValidators.vue]: we don't want to sort by rewards ?

File: test/unit/specs/components/staking/TableValidators.spec.js [hunk 2]
```diff
@@ -100,101 +79,61 @@ describe(`TableValidators`, () => {
...
-        }
-      ]
-      const session = { signedIn: true }
-      const $store = { dispatch: jest.fn() }
-      TableValidators.watch.validators.call({ $store, session }, validators)
-      expect($store.dispatch).toHaveBeenCalledWith(
-        `getRewardsFromAllValidators`,
-        validators
-      )
+  xit(`updates if there are existing validators`, () => {
```
Comment (jbibla) [inline test/unit/specs/components/staking/TableValidators.spec.js]: i could use some help with this test @faboweb

File: app/src/renderer/components/staking/TableValidators.vue [hunk 3]
```diff
@@ -39,100 +37,102 @@ export default {
...
-          v.voting_power = v.voting_power ? Number(v.voting_power) : 0
-          return v
-        })
-        .sort((a, b) => b.voting_power - a.voting_power)
-        .slice(0, 100)
-        .reduce((sum, v) => sum + v.voting_power, 0)
-    },
-    enrichedDelegates() {
-      return this.validators.map(v =>
+    enrichedValidators({
```
Comment (jbibla) [inline app/src/renderer/components/staking/TableValidators.vue]: this should be happening somewhere else / refactored (#1380 #2306) but moving it would be a big task so i just made sure it worked and was tested... because previously it didn't work and wasn't tested.

File: test/unit/specs/components/staking/__snapshots__/LiValidator.spec.js.snap [hunk 4]
```diff
@@ -74,17 +82,86 @@ exports[`LiValidator has the expected html structure 1`] = `
...
+    22.00%
+  
+  </td>
    
   <td
     class="li-validator__commission"
   >
     
-    0.05%
+    500.00%
```
Comment (faboweb) [inline test/unit/specs/components/staking/__snapshots__/LiValidator.spec.js.snap]: looks like a lot ^^
