### PR TITLE
Jordan/2188 page network bug

### LINKED ISSUE #2188: Network page error message is incorrect
**Describe the bug**

Network page error message is incorrect while cosmos wallet is trying to connect to a node.

**To Reproduce**

- open cosmos wallet without being connected to the API
- go to network page

**Expected behavior**

Should show the waiting for connection component.

**Screenshots**

screen shot 2019-03-06 at 7 48 02 am

### PR DESCRIPTION
**Pull request by jbibla**
Closes #2188 

**Description:**

- using TmPage loading, loaded, dataset props
- updated Connecting Msg copy
- added `blocks.loaded` to module

Thank you! 🚀

---

For contributor:

- [ ] Added entries in `PENDING.md` with issue # and GitHub username
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: app/src/renderer/components/common/TmPage.vue [hunk 1]
```diff
@@ -87,7 +87,7 @@ export default {
       default: undefined
     },
     dataset: {
-      type: Array,
+      type: [Array, Object],
```
Comment (jbibla) [inline app/src/renderer/components/common/TmPage.vue]: i know we agreed to not permit this. however, this might be time for an exception _or_ please share a suggestion for how to avoid this.

File: app/src/renderer/components/network/PageNetwork.vue [hunk 2]
```diff
@@ -1,7 +1,12 @@
 <template>
-  <tm-page data-title="Network">
-    <tm-data-error v-if="!connected" />
-    <template v-else>
+  <tm-page
+    :loading="blocks.loading"
+    :loaded="blocks.loaded"
+    :error="blocks.error"
+    :dataset="lastHeader"
```
Comment (jbibla) [inline app/src/renderer/components/network/PageNetwork.vue]: page network is a bit strange because it doesn't need the "items" (dataset) to load. it just needs a `connection` to render the top part of the page. the `blocks` are the second "dataset". `lastHeader` and `connection` don't have loading, loaded, or error states...

reveals room for a refactor - but this might be sufficient for now.

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (faboweb) [reply app/src/renderer/components/common/TmPage.vue]: this needs to be an array or more then this needs to be refactored. see line 28

Comment (faboweb) [reply app/src/renderer/components/common/TmPage.vue]: proposal: change to "dataAvailable" and make it a boolean. checks are then performed on each page on the individual dataset

Comment (sabau) [reply app/src/renderer/components/common/TmPage.vue]: Also cheaper to pass

File: app/src/renderer/components/network/PageNetwork.vue (hunk 2 above)
Comment (sabau) [reply app/src/renderer/components/network/PageNetwork.vue]: I think we have in the store the list of blocks, but I like more @faboweb idea of booleanize

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (jbibla) [reply app/src/renderer/components/common/TmPage.vue]: ok makes sense. do you guys think this should be done in this PR and not separately?

File: app/src/renderer/components/network/PageNetwork.vue (hunk 2 above)
Comment (jbibla) [reply app/src/renderer/components/network/PageNetwork.vue]: me too

File: app/src/renderer/components/common/TmPage.vue (hunk 1 above)
Comment (faboweb) [reply app/src/renderer/components/common/TmPage.vue]: let's do it in here. the change needs to happen in only 3 places and we don't pile up more dept.

Comment (jbibla) [reply app/src/renderer/components/common/TmPage.vue]: > in only 3 places

yeah. one line 😝

**Comment by sabau** [comment]
I think this should be merged right after TmPage and PageNetwork stuff is done, all good and and is a bug fix

File: PENDING.md [hunk 3]
```diff
@@ -1,4 +1,17 @@
+### Added
+
+- [\#2104](https://github.com/cosmos/voyager/issues/2104) fix transaction times @fedekunze
```
Comment (fedekunze) [inline PENDING.md]: why so many `PENDING` entries ?

File: app/src/renderer/components/governance/PageGovernance.vue [hunk 4]
```diff
@@ -1,11 +1,5 @@
 <template>
-  <tm-page
-    :tabs="tabs"
-    :dataset="proposalList"
-    search="proposals"
-    class="governance"
-    data-title="Governance"
-  >
+  <tm-page :tabs="tabs" class="governance" data-title="Governance">
```
[the remark this answers is not in the document]
Comment (jbibla) [reply app/src/renderer/components/governance/PageGovernance.vue]: yeah, it should be covered in the proposal tab though, not up here.
